Sprint 3
EranosyanEduard/middle.messenger.praktikum.yandex pull request #3
Opened 2022-05-23 07:40 UTC by EranosyanEduard

Здравствуйте.

Для того, чтобы удалить чат или его пользователей необходимо кликать правой кнопкой мыши по определенному чату.
С тестированием роутера возникли трудности, поскольку необходимо подменять оригинальные интерфейсы с помощью пакета jsdom, работа которого отличается от оригинальных интерфейсов браузера (методы back и forward).

2022-05-23 08:26 UTC, EranosyanEduard commented
Перед запуском тестов - запустите скрипт "npm run before_test".

2022-05-23 17:10 UTC, podlovchenko requested changes
Привет, интересная архитектура приложения)
Есть замечания по работе системы:
1. Нет редиректа на страницу чатов, если пользователь в системе
2. При обновление страницы Cannot GET
3. Не получилось загрузить аватар

2022-05-25 07:03 UTC, podlovchenko commented
Привет, не могу войти в систему, ответ от сервера `User already in system`, а редиректа на страницу чатов нет, но со страницы чатов есть редирект на форму входа

2022-05-25 07:13 UTC, podlovchenko commented
Я запускала через `npm run serve`
Через `npm run start` работает
Переоткрой, я приму работу
Но нужно будет разобраться с командами и запусками в dev режиме (здесь достаточно parcel serve, посмотри почему не работает редирект, или parcel build и nodemon)  и в режиме продакшена (здесь parcel build и node)

2022-05-25 07:15 UTC, EranosyanEduard commented
Ничего не менял, отправил повторно, как вы и просили.

2022-05-25 07:23 UTC, podlovchenko approved these changes

2022-05-26 03:29 UTC, merged